language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - platform-tools
    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script: gradle check